---
kind: List
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: demo-api
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: demo-api
      spec:
        containers:
        - name: demo-api
          image: bturbes/demo_api
          ports:
          - containerPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    name: demo-api
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
    selector:
      app: demo-api
      
