version: '2'
services:
  web:
    image: golang
    command: sh -c "go build && ./demo_api"
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/github.com/bturbes/demo_api"
    working_dir: /go/src/github.com/bturbes/demo_api
